export const TYPES = {
  GET_MOVIE_DETAILS_REQUEST: "GET_MOVIE_DETAILS_REQUEST",
  GET_MOVIE_DETAILS_SUCCESS: "GET_MOVIE_DETAILS_SUCCESS",
  GET_MOVIE_DETAILS_FAILURE: "GET_MOVIE_DETAILS_FAILURE",
};
