export const TYPES = {
  GET_MOVIES_REQUEST: "GET_MOVIES_REQUEST",
  GET_MOVIES_SUCCESS: "GET_MOVIES_SUCCESS",
  GET_MOVIES_FAILURE: "GET_MOVIES_FAILURE,",

  GET_LIVE_SEARCH_MOVIES_REQUEST: "GET_LIVE_SEARCH_MOVIES_REQUEST",
  GET_LIVE_SEARCH_MOVIES_SUCCESS: "GET_LIVE_SEARCH_MOVIES_SUCCESS",
  GET_LIVE_SEARCH_MOVIES_FAILURE: "GET_LIVE_SEARCH_MOVIES_FAILURE,",

  SET_TOTAL_RESULTS: "SET_TOTAL_RESULTS",
};
