export const TYPES = {
  SET_SEARCH_PARAMS: "SET_SEARCH_PARAMS",
  SET_LIVE_SEARCH_PARAMS: "SET_LIVE_SEARCH_PARAMS",

  INCREMENT_PAGE: "INCREMENT_PAGE",
  DECREMENT_PAGE: "DECREMENT_PAGE",
  RESET_PAGE: "RESET_PAGE",
};
