export const TYPES = {
  OPEN_HEADER_COLLAPSE: "OPEN_HEDER_COLLAPSE",
  CLOSE_HEADER_COLLAPSE: "CLOSE_HEADER_COLLAPSE",

  OPEN_SEARCH_COLLAPSE: "OPEN_SEARCH_COLLAPSE",
  CLOSE_SEARCH_COLLAPSE: "CLOSE_SEARCH_COLLAPSE",
};
